version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'Admin123!'
    ports:
      - '1433:1433'
    volumes:
      - mssqldata:/var/opt/mssql

volumes:
  mssqldata:
